# Site settings
title: TCAC
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Truth Chinese Alliance Church in El Monte, CA!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://truthalliancechurch.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
